# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pj_kinta_kun' do
  use_frameworks!

  pod 'SnapKit'

  target 'pj_kinta_kunTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
